#! /usr/bin/env bash

#########################################################################
#									#
# Script ID: .pbuilderrc						#
# Based on an outline by Stein Magnus Jodal				#
#	https://jodal.no/2015/03/08/building-arm-debs-with-pbuilder/	#
# Author: Copyright (C) 2018-2020  Mark Grant				#
#									#
# Released under the GPLv3 only.					#
# SPDX-License-Identifier: GPL-3.0					#
#									#
# Purpose:								#
# This pbuilderrc file sets up pbuilder to be able to build for OS's,	#
# distributions and architectures. These values should be passed on the	#
# command line. E.g.							#
#	sudo OS=raspbian DIST=stretch ARCH=armhf APT_CACHER=yes \	#
#		pbuilder create --override-config \			#
#		--debootstrapopts --variant=buildd			#
#									#
#########################################################################

#########################################################################
#									#
# Changelog								#
#									#
# Date		Author	Version	Description				#
#									#
# 22/02/2018	MG	1.0.1	Created.				#
# 17/05/2018	MG	1.0.2	Add staging component.			#
#				Add AUTOCLEANAPTCACHE=yes which does an	#
#				apt-get autoclean on the cache.		#
# 19/10/2018	MG	1.0.3	Add Bintray to OTHERMIRROR.		#
# 04/02/2019	MG	1.0.4	Update OTHERMIRROR for new source	#
#				tarball repo on hermes.			#
#				Add vim as an extra package.		#
# 29/07/2019	MG	1.0.5	Use OS and DIST in OTHERMIRROR.		#
#				Correct example create CL above.	#
#				Add security & updates to OTHERMIRROR.	#
#				Remove Ubuntu as not maintained and	#
#				possibly misleading.			#
#				Correct Purpose section above.		#
#				Do not set OTHERMIRROR when creating	#
#				the archive as it will fail due to	#
#				missing keys.				#
# 19/10/2019	MG	1.0.6	Change Bintray Debian repo name. Change	#
#				Raspbian to use Bintray.		#
# 10/11/2019	MG	1.0.7	Change example CL invocation above to	#
#				remove unnecessary --override-config.	#
#				Add support for Ubuntu.			#
# 28/02/2020	MG	1.1.0	Add support for apt-cacher-ng.		#
#				Tidy up MIRRORSITE & OTHERMIRRORS.	#
#				Remove double logging of		#
#				DEBOOTSTRAPOPTS.			#
#				Correct logging of DEBOOTSTRAPOPTS.	#
#				Prefer printf over echo.		#
#				Add accreditation for Stein Magnus Jodal#
#				Allow pbuilder create to use these	#
#				OTHERMIRROR settings with		#
#				--override-config.			#
#				Add PPA to ubuntu OTHERMIRROR.		#
# 02/05/2020	MG	1.1.1	Ubuntu hermes repository now exists, so	#
#				use it.					#
#				Correct aptkeyrings handling.		#
#				Add extra package apt-utils.		#
#									#
#########################################################################


#############################
# Exit immediately on error #
#############################
set -e


##################
# Init variables #
##################
OTHERMIRROR=""


#########################################################################
# Determine the start of the apt list line as it is different depending	#
# on whether apt-cacher-ng is available.				#
#########################################################################
if [[ $APT_CACHER == "" ]]; then
	APT_CACHER=yes
fi

# APT_CACHER == yes implies that not only the cache is available but also the
# local repository. A no implies the opposite.
case $APT_CACHER in
yes)
	http_prefix="http://hermes.mgent.home:3142"
	https_prefix="http://hermes.mgent.home:3142/HTTPS//"
	;;
no)
	http_prefix="http:/"
	https_prefix="https:/"
	;;
*)
	printf "Unknown APT_CACHER value: %s\n" $APT_CACHER
	exit 1
	;;
esac


########################################################
# OTHERMIRROR may be added to later so initialise here #
########################################################
if [[ $APT_CACHER == yes ]]; then
	OTHERMIRROR="deb http://hermes.mgent.home/aptrepos/$OS $DIST "
	OTHERMIRROR+="beta stable staging"
	APTKEYRINGS=("/etc/apt/trusted.gpg.d/hermes-keyring.gpg")
fi


########################
# OS specific settings #
########################
case $OS in
debian)
	MIRRORSITE="$https_prefix/deb.debian.org/debian/"
	COMPONENTS="main contrib non-free"
	if [[ $OTHERMIRROR != "" ]]; then
		OTHERMIRROR+="|"
	fi
	OTHERMIRROR+="deb $https_prefix/deb.debian.org/debian-security/ "
	OTHERMIRROR+="$DIST/updates main contrib non-free"
	OTHERMIRROR+="|deb $https_prefix/deb.debian.org/debian $DIST-updates "
	OTHERMIRROR+="main contrib non-free"
	DEBOOTSTRAPOPTS=("${DEBOOTSTRAPOPTS[@]}"
		"--keyring=/usr/share/keyrings/debian-archive-keyring.gpg")

	OTHERMIRROR+="|deb $https_prefix/dl.bintray.com/mgrantprg/debian-utils "
	OTHERMIRROR+="$DIST stable"
	APTKEYRINGS=("${APTKEYRINGS[@]}"
		"/etc/apt/trusted.gpg.d/bintray-keyring.gpg")
	;;
raspbian)
	MIRRORSITE="$http_prefix/mirrordirector.raspbian.org/raspbian/"
	COMPONENTS="main contrib non-free rpi"
	if [[ $OTHERMIRROR != "" ]]; then
		OTHERMIRROR+="|"
	fi
	OTHERMIRROR+="deb $http_prefix/archive.raspberrypi.org/debian/ "
	OTHERMIRROR+="$DIST main ui"
	DEBOOTSTRAPOPTS=("${DEBOOTSTRAPOPTS[@]}"
		"--keyring=/usr/share/keyrings/raspbian-archive-keyring.gpg")

	OTHERMIRROR+="|deb $https_prefix/dl.bintray.com/mgrantprg/"
	OTHERMIRROR+="raspbian-utils $DIST stable"
	APTKEYRINGS=("${APTKEYRINGS[@]}"
		"/etc/apt/trusted.gpg.d/bintray-keyring.gpg")
	;;
ubuntu)
	MIRRORSITE="$http_prefix/uk.archive.ubuntu.com/ubuntu/"
	COMPONENTS="main restricted universe multiverse"
	if [[ $OTHERMIRROR != "" ]]; then
		OTHERMIRROR+="|"
	fi
	OTHERMIRROR+="deb $http_prefix/uk.archive.ubuntu.com/ubuntu/ "
	OTHERMIRROR+="$DIST-security "
	OTHERMIRROR+="main restricted universe multiverse"
	OTHERMIRROR+="|deb $http_prefix/uk.archive.ubuntu.com/ubuntu/ "
	OTHERMIRROR+="$DIST-updates "
	OTHERMIRROR+="main restricted universe multiverse"
	DEBOOTSTRAPOPTS=("${DEBOOTSTRAPOPTS[@]}"
		"--keyring=/usr/share/keyrings/ubuntu-archive-keyring.gpg")

	OTHERMIRROR+="|deb $http_prefix/ppa.launchpad.net/m-grant-prg/utils/"
	OTHERMIRROR+="$OS $DIST main"
	APTKEYRINGS=("${APTKEYRINGS[@]}"
		"/etc/apt/trusted.gpg.d/mgrant-utils-ppa-keyring.gpg")
	;;
*)
	printf "Unknown OS: %s\n" $OS
	exit 1
	;;
esac


##############################################
# Check we now have a value of DIST and ARCH #
##############################################
if [ "$DIST" == "" ]; then
	printf "DIST is not set\n"
	exit 1
fi

if [ "$ARCH" == "" ]; then
	printf "ARCH is not set\n"
	exit 1
fi


#####################################################
# We always need these packages in the base tarball #
#####################################################
EXTRAPACKAGES+=" apt-utils dirmngr gnupg2 software-properties-common vim wget"


###################################
# Deal with potential cross-build #
###################################
if [ "$ARCH" == "armel" ] && [ "$(dpkg --print-architecture)" != "armel" ]; then
    DEBOOTSTRAP="qemu-debootstrap"
fi
if [ "$ARCH" == "armhf" ] && [ "$(dpkg --print-architecture)" != "armhf" ]; then
    DEBOOTSTRAP="qemu-debootstrap"
fi


########################
# Add the Architecture #
########################
DEBOOTSTRAPOPTS=("${DEBOOTSTRAPOPTS[@]}" "--arch=$ARCH")


####################
# Self explanatory #
####################
BASETGZ="/var/cache/pbuilder/$OS-$DIST-$ARCH-base.tgz"

DISTRIBUTION="$DIST"

PBUILDERSATISFYDEPENDSCMD=/usr/lib/pbuilder/pbuilder-satisfydepends-apt

BUILDRESULT="/home/mgrantprg/SWDev/pbuilder/$OS-$DIST-$ARCH-result/"

APTCACHE="/var/cache/pbuilder/aptcache/$OS-$DIST-$ARCH/"

AUTOCLEANAPTCACHE=yes


##########################################################################
# Hook scripts are executed during chroot setup, before packaging begins #
##########################################################################
HOOKDIR="/home/mgrantprg/SWDev/pbuilder/hook.d/"


#####################
# Now log the setup #
#####################
psetuplog="$BUILDRESULT""pbuilderrc-setup.log"

printf "OS = %s\n" "$OS" > $psetuplog
printf "Distribution = %s\n" "$DIST" >> $psetuplog
printf "Arch = %s\n" "$ARCH" >> $psetuplog
printf "APT_CACHER = %s\n" "$APT_CACHER" >> $psetuplog
printf "Mirrorsite = %s\n" "$MIRRORSITE" >> $psetuplog
printf "Components = %s\n" "$COMPONENTS" >> $psetuplog
printf "Othermirror = %s\n" "$OTHERMIRROR" >> $psetuplog
printf "Aptkeyrings = %s\n" "${APTKEYRINGS[@]}" >> $psetuplog
printf "Extrapackages = %s\n" "$EXTRAPACKAGES" >> $psetuplog
printf "Debootstrap = %s\n" "$DEBOOTSTRAP" >> $psetuplog
printf "Debootstrapopts = %s\n" "${DEBOOTSTRAPOPTS[@]}" >> $psetuplog
printf "Basetgz = %s\n" "$BASETGZ" >> $psetuplog
printf "Pbuildersatisfydependscmd = %s\n" "$PBUILDERSATISFYDEPENDSCMD" >> $psetuplog
printf "Buildresult = %s\n" "$BUILDRESULT" >> $psetuplog
printf "Aptcache = %s\n" "$APTCACHE" >> $psetuplog
printf "Hookdir = %s\n" "$HOOKDIR" >> $psetuplog

