#! /usr/bin/env bash

#########################################################################
#									#
# Based on an outline by Stein Magnus Jodal				#
#	https://jodal.no/2015/03/08/building-arm-debs-with-pbuilder/	#
# Author: Copyright (C) 2018-2025  Mark Grant				#
#									#
# This file is maintained in the project at:-				#
#	https://github.com/m-grant-prg/pbuilder-config			#
#		new versions are merely copied to consumer projects.	#
#									#
# Released under the GPLv3 only.					#
# SPDX-License-Identifier: GPL-3.0-only					#
#									#
# Purpose:								#
# This pbuilderrc file provides a mechanism for pbuilder to be able to	#
# build for different distributions, releases and architectures. This	#
# information is conveyed on the command line. E.g.			#
#	sudo DIST=rpios REL=stretch ARCH=armhf APT_CACHER=yes \	#
#		pbuilder create --override-config \			#
#		--debootstrapopts --variant=buildd			#
#									#
#########################################################################

#########################################################################
#									#
# Version	v1.1.19							#
#									#
#########################################################################


#############################
# Exit immediately on error #
#############################
set -e


##################
# Init variables #
##################
declare -i num_rel	# Numeric release value
OTHERMIRROR=""


#############
# Functions #
#############

# Basic Debian setup which can be used for rpios on arm64 etc which utilise
# Debian repos.
# No parameters
# No return value
debian_basic_setup()
{
	MIRRORSITE="$https_prefix/deb.debian.org/debian/"
	COMPONENTS="main contrib non-free"
	DEBOOTSTRAPOPTS=("${DEBOOTSTRAPOPTS[@]}"
		"--keyring=/usr/share/keyrings/debian-archive-keyring.gpg")
	if [[ $OTHERMIRROR != "" ]]; then
		OTHERMIRROR+="|"
	fi
	OTHERMIRROR+="deb $https_prefix/deb.debian.org/debian-security/ "
	OTHERMIRROR+="$REL-security main contrib non-free"
	OTHERMIRROR+="|deb $https_prefix/deb.debian.org/debian $REL-updates "
	OTHERMIRROR+="main contrib non-free"
	OTHERMIRROR+="|deb http://download.opensuse.org/repositories/home:"
	OTHERMIRROR+="/m-grant-prg/Debian_$obs_rel/ /"
	APTKEYRINGS=("${APTKEYRINGS[@]}"
		"/etc/apt/trusted.gpg.d/home_m-grant-prg.gpg")
}


#########################################################################
# OpenSUSE Build Service needs a numeric string release for Debian and	#
# rpios stable releases and a numeric value is needed for changes	#
# such as >= release. The following is valid for buster onwards with a	#
# quirk for the OBS Debian Testing version.				#
#########################################################################
if [[ $DIST == "debian" || $DIST == "rpios" ]];then
	if [[ $REL == "testing" ]];then
		num_rel=$(distro-info -r --testing)
		obs_rel="Testing"
	else
		num_rel=$(distro-info -r --series=$REL)
		obs_rel=$num_rel
	fi
fi


#########################################################################
# Determine the start of the apt list line as it is different depending	#
# on whether apt-cacher-ng is available.				#
#########################################################################
if [[ $APT_CACHER == "" ]]; then
	APT_CACHER=yes
fi

# APT_CACHER == yes implies that not only the cache is available but also the
# local repository. A no implies the opposite.
case $APT_CACHER in
yes)
	http_prefix="http://hermes.mgent.home:3142"
	https_prefix="http://hermes.mgent.home:3142/HTTPS//"
	;;
no)
	http_prefix="http:/"
	https_prefix="https:/"
	;;
*)
	printf "Unknown APT_CACHER value: %s\n" $APT_CACHER
	exit 1
	;;
esac


########################################################
# OTHERMIRROR may be added to later so initialise here #
########################################################
if [[ $APT_CACHER == yes ]]; then
	OTHERMIRROR="deb http://hermes.mgent.home/aptrepos/$DIST $REL "
	OTHERMIRROR+="alpha beta stable staging"
	APTKEYRINGS=("/etc/apt/trusted.gpg.d/hermes-keyring.gpg")
fi


##########################
# DIST specific settings #
##########################
case $DIST in
debian)
	debian_basic_setup
	;;
rpios)
	# arm64 onwards uses the standard Debian repositories.
	if [[ $ARCH == "armhf" || $ARCH == "armel" ]]; then
		MIRRORSITE="$http_prefix/mirrordirector.raspbian.org/raspbian/"
		COMPONENTS="main contrib non-free rpi"
		DEBOOTSTRAPOPTS=("${DEBOOTSTRAPOPTS[@]}"
		   "--keyring=/usr/share/keyrings/raspbian-archive-keyring.gpg")
		if [[ $OTHERMIRROR != "" ]]; then
			OTHERMIRROR+="|"
		fi
		OTHERMIRROR+="deb http://download.opensuse.org/repositories"
		OTHERMIRROR+="/home:/m-grant-prg/Raspbian_$obs_rel/ /"
		APTKEYRINGS=("${APTKEYRINGS[@]}"
			"/etc/apt/trusted.gpg.d/home_m-grant-prg.gpg")
	else
		debian_basic_setup
	fi
	OTHERMIRROR+="|deb $http_prefix/archive.raspberrypi.org/debian/ "
	OTHERMIRROR+="$REL main"
	APTKEYRINGS=("${APTKEYRINGS[@]}"
		"/etc/apt/trusted.gpg.d/raspberrypi-keyring.gpg")
	;;
ubuntu)
	MIRRORSITE="$http_prefix/uk.archive.ubuntu.com/ubuntu/"
	COMPONENTS="main restricted universe multiverse"
	DEBOOTSTRAPOPTS=("${DEBOOTSTRAPOPTS[@]}"
		"--keyring=/usr/share/keyrings/ubuntu-archive-keyring.gpg")
	if [[ $OTHERMIRROR != "" ]]; then
		OTHERMIRROR+="|"
	fi
	OTHERMIRROR+="deb $http_prefix/uk.archive.ubuntu.com/ubuntu/ "
	OTHERMIRROR+="$REL-security "
	OTHERMIRROR+="main restricted universe multiverse"
	OTHERMIRROR+="|deb $http_prefix/uk.archive.ubuntu.com/ubuntu/ "
	OTHERMIRROR+="$REL-updates "
	OTHERMIRROR+="main restricted universe multiverse"
	OTHERMIRROR+="|deb $http_prefix/ppa.launchpad.net/m-grant-prg/utils/"
	OTHERMIRROR+="$DIST $REL main"
	APTKEYRINGS=("${APTKEYRINGS[@]}"
		"/etc/apt/trusted.gpg.d/mgrant-utils-ppa-keyring.gpg")
	;;
*)
	printf "Unknown DIST: %s\n" $DIST
	exit 1
	;;
esac


#############################################
# Check we now have a value of REL and ARCH #
#############################################
if [ "$REL" == "" ]; then
	printf "REL is not set\n"
	exit 1
fi

if [ "$ARCH" == "" ]; then
	printf "ARCH is not set\n"
	exit 1
fi


#####################################################
# We always need these packages in the base tarball #
#####################################################
EXTRAPACKAGES+=" apt-utils curl dirmngr gnupg2 vim"


########################
# Add the Architecture #
########################
DEBOOTSTRAPOPTS=("${DEBOOTSTRAPOPTS[@]}" "--arch=$ARCH")


#############################################################################
# Non-existent user id for non-root build and user name for use by fakeroot #
#############################################################################
BUILDUSERID=1234
BUILDUSERNAME=pbuilder


####################
# Self explanatory #
####################
BASETGZ="/var/cache/pbuilder/$DIST-$REL-$ARCH-base.tgz"

DISTRIBUTION="$REL"

PBUILDERSATISFYDEPENDSCMD=/usr/lib/pbuilder/
PBUILDERSATISFYDEPENDSCMD+=pbuilder-satisfydepends-apt

BUILDRESULT="/home/mgrantprg/SWDev/pbuilder/$DIST-$REL-$ARCH-result/"

APTCACHE="/var/cache/pbuilder/aptcache/$DIST-$REL-$ARCH/"

AUTOCLEANAPTCACHE=yes


##########################################################################
# Hook scripts are executed during chroot setup, before packaging begins #
##########################################################################
HOOKDIR="/home/mgrantprg/SWDev/pbuilder/hook.d/"


#####################
# Now log the setup #
#####################
psetuplog="$BUILDRESULT""pbuilderrc-setup.log"

printf "Distribution = %s\n" "$DIST" > $psetuplog
printf "Release = %s\n" "$REL" >> $psetuplog
printf "Numeric Release = %i\n" "$num_rel" >> $psetuplog
printf "Arch = %s\n" "$ARCH" >> $psetuplog
printf "APT_CACHER = %s\n" "$APT_CACHER" >> $psetuplog
printf "Mirrorsite = %s\n" "$MIRRORSITE" >> $psetuplog
printf "Components = %s\n" "$COMPONENTS" >> $psetuplog
printf "Othermirror = %s\n" "$OTHERMIRROR" >> $psetuplog
printf "Aptkeyrings = %s\n" "${APTKEYRINGS[@]}" >> $psetuplog
printf "Extrapackages = %s\n" "$EXTRAPACKAGES" >> $psetuplog
printf "Builduserid = %s\n" "$BUILDUSERID" >> $psetuplog
printf "Buildusername = %s\n" "$BUILDUSERNAME" >> $psetuplog
printf "Debootstrap = %s\n" "$DEBOOTSTRAP" >> $psetuplog
printf "Debootstrapopts = %s\n" "${DEBOOTSTRAPOPTS[@]}" >> $psetuplog
printf "Basetgz = %s\n" "$BASETGZ" >> $psetuplog
printf "Pbuildersatisfydependscmd = %s\n" "$PBUILDERSATISFYDEPENDSCMD" >> $psetuplog
printf "Buildresult = %s\n" "$BUILDRESULT" >> $psetuplog
printf "Aptcache = %s\n" "$APTCACHE" >> $psetuplog
printf "Hookdir = %s\n" "$HOOKDIR" >> $psetuplog

